import prisma from '../lib/prisma';
import { QuestionType, Difficulty, QuestionStatItem, DimensionStatItem, ScoreDistributionItem } from '../types';

export interface AutoGenerateParams {
  subject: string;
  questionTypes: QuestionType[];
  totalScore: number;
  difficulty?: Difficulty;
  title?: string;
  duration?: number;
  userId: number;
}

export interface AutoGenerateResult {
  questionId: number;
  score: number;
  sortOrder: number;
}

export async function generatePaperItems(params: AutoGenerateParams): Promise<{
  items: AutoGenerateResult[];
  actualTotal: number;
}> {
  const { subject, questionTypes, totalScore, difficulty } = params;

  const where: any = { subject };
  if (difficulty) where.difficulty = difficulty;
  if (questionTypes.length > 0) where.type = { in: questionTypes };

  const questions = await prisma.question.findMany({ where });
  if (questions.length === 0) {
    return { items: [], actualTotal: 0 };
  }

  const shuffled = questions.sort(() => Math.random() - 0.5);

  let remainingScore = totalScore;
  const selectedItems: AutoGenerateResult[] = [];
  let sortOrder = 1;

  for (const q of shuffled) {
    if (remainingScore <= 0) break;
    const score = Math.min(q.score, remainingScore);
    selectedItems.push({ questionId: q.id, score, sortOrder });
    remainingScore -= score;
    sortOrder++;
  }

  const actualTotal = selectedItems.reduce((sum, item) => sum + item.score, 0);

  return { items: selectedItems, actualTotal };
}

export async function createAutoGeneratedPaper(params: AutoGenerateParams) {
  const { items, actualTotal } = await generatePaperItems(params);

  if (items.length === 0) {
    return null;
  }

  const title = params.title || `${params.subject}自动生成试卷`;
  const description = `自动生成 - 难度: ${params.difficulty || '混合'} - 总分: ${actualTotal}`;
  const duration = params.duration || Math.ceil(items.length * 2);

  const paper = await prisma.paper.create({
    data: {
      title,
      description,
      totalScore: actualTotal,
      duration,
      createdBy: params.userId,
      items: { create: items },
    },
    include: { items: { include: { question: true }, orderBy: { sortOrder: 'asc' } } },
  });

  return paper;
}

export async function updatePaperWithAutoGenerate(paperId: number, params: Omit<AutoGenerateParams, 'userId' | 'title' | 'duration'>) {
  const existing = await prisma.paper.findUnique({ where: { id: paperId } });
  if (!existing) {
    return null;
  }

  const { items, actualTotal } = await generatePaperItems({
    ...params,
    userId: existing.createdBy,
  });

  if (items.length === 0) {
    return null;
  }

  await prisma.paperItem.deleteMany({ where: { paperId } });
  const paper = await prisma.paper.update({
    where: { id: paperId },
    data: {
      totalScore: actualTotal,
      items: { create: items },
    },
    include: { items: { include: { question: true }, orderBy: { sortOrder: 'asc' } } },
  });

  return paper;
}

export function calculateExamScore(
  paperItems: Array<{
    id: number;
    questionId: number;
    score: number;
    question: { type: string; answer: string };
  }>,
  answers: Record<number, string> | undefined,
): number {
  let totalScore = 0;

  for (const item of paperItems) {
    const userAnswer = answers ? answers[item.questionId] : undefined;
    if (userAnswer !== undefined && userAnswer !== null && userAnswer !== '') {
      const correctAnswer = item.question.answer;
      if (isAnswerCorrect(item.question.type, userAnswer, correctAnswer)) {
        totalScore += item.score;
      }
    }
  }

  return totalScore;
}

export function isAnswerCorrect(
  questionType: string,
  userAnswer: string,
  correctAnswer: string,
): boolean {
  if (
    questionType === 'SINGLE_CHOICE' ||
    questionType === 'TRUE_FALSE' ||
    questionType === 'FILL_BLANK'
  ) {
    return String(userAnswer).trim().toLowerCase() === String(correctAnswer).trim().toLowerCase();
  } else if (questionType === 'MULTIPLE_CHOICE') {
    const userSorted = String(userAnswer)
      .split(',')
      .map((s) => s.trim())
      .sort()
      .join(',');
    const correctSorted = String(correctAnswer)
      .split(',')
      .map((s) => s.trim())
      .sort()
      .join(',');
    return userSorted === correctSorted;
  }
  return false;
}

export interface WrongQuestionItem {
  questionId: number;
  userAnswer: string | undefined;
  correctAnswer: string;
  subject: string;
}

export function getWrongQuestions(
  paperItems: Array<{
    id: number;
    questionId: number;
    score: number;
    question: { id: number; type: string; answer: string; subject: string };
  }>,
  answers: Record<number, string> | undefined,
): WrongQuestionItem[] {
  const wrongItems: WrongQuestionItem[] = [];

  for (const item of paperItems) {
    const userAnswer = answers ? answers[item.questionId] : undefined;
    const isCorrect = userAnswer !== undefined && userAnswer !== null && userAnswer !== ''
      ? isAnswerCorrect(item.question.type, userAnswer, item.question.answer)
      : false;

    if (!isCorrect) {
      wrongItems.push({
        questionId: item.questionId,
        userAnswer: userAnswer,
        correctAnswer: item.question.answer,
        subject: item.question.subject,
      });
    }
  }

  return wrongItems;
}

export function isObjectiveQuestion(questionType: string): boolean {
  return (
    questionType === 'SINGLE_CHOICE' ||
    questionType === 'MULTIPLE_CHOICE' ||
    questionType === 'TRUE_FALSE' ||
    questionType === 'FILL_BLANK'
  );
}

export function roundToTwo(num: number): number {
  return Math.round(num * 100) / 100;
}

export function buildScoreRanges(totalScore: number): Array<{ range: string; min: number; max: number }> {
  const ranges: Array<{ range: string; min: number; max: number }> = [];
  const interval = Math.ceil(totalScore / 10);

  for (let i = 0; i < 10; i++) {
    const min = i * interval;
    const max = i === 9 ? totalScore : (i + 1) * interval - 0.01;
    const rangeLabel = i === 9
      ? `${Math.floor(min)}-${totalScore}`
      : `${Math.floor(min)}-${Math.floor((i + 1) * interval - 1)}`;
    ranges.push({ range: rangeLabel, min, max });
  }

  return ranges;
}

export function calculateScoreDistribution(
  scores: number[],
  ranges: Array<{ range: string; min: number; max: number }>
): ScoreDistributionItem[] {
  const total = scores.length;

  return ranges.map((r) => {
    const count = scores.filter((s) => s >= r.min && s <= r.max).length;
    return {
      range: r.range,
      min: r.min,
      max: r.max,
      count,
      percentage: total > 0 ? roundToTwo(count / total) : 0,
    };
  });
}

interface PaperItemForStats {
  questionId: number;
  sortOrder: number;
  score: number;
  question: {
    type: string;
    content: string;
    answer: string;
    difficulty: string;
    subject: string;
  };
}

interface ExamRecordForStats {
  answers: Record<number, string> | undefined;
}

export function calculateQuestionStats(
  paperItems: PaperItemForStats[],
  submittedRecords: ExamRecordForStats[]
): QuestionStatItem[] {
  if (submittedRecords.length === 0) {
    return paperItems.map((item) => ({
      questionId: item.questionId,
      sortOrder: item.sortOrder,
      type: item.question.type,
      content: item.question.content,
      score: item.score,
      difficulty: item.question.difficulty,
      subject: item.question.subject,
      correctCount: 0,
      wrongCount: 0,
      unansweredCount: 0,
      ungradedCount: 0,
      accuracyRate: 0,
      avgScore: 0,
      scoreRate: 0,
      isObjective: isObjectiveQuestion(item.question.type),
    }));
  }

  const totalRecords = submittedRecords.length;

  return paperItems.map((item) => {
    let correctCount = 0;
    let wrongCount = 0;
    let unansweredCount = 0;
    let ungradedCount = 0;
    let totalGotScore = 0;

    const objective = isObjectiveQuestion(item.question.type);

    for (const record of submittedRecords) {
      const userAnswer = record.answers ? record.answers[item.questionId] : undefined;
      const hasAnswer = userAnswer !== undefined && userAnswer !== null && userAnswer !== '';

      if (!hasAnswer) {
        unansweredCount++;
        continue;
      }

      if (!objective) {
        ungradedCount++;
        continue;
      }

      const correct = isAnswerCorrect(item.question.type, userAnswer, item.question.answer);

      if (correct) {
        correctCount++;
        totalGotScore += item.score;
      } else {
        wrongCount++;
      }
    }

    const gradedCount = correctCount + wrongCount;
    const accuracyRate = gradedCount > 0 ? roundToTwo(correctCount / gradedCount) : 0;
    const avgScore = totalRecords > 0 ? roundToTwo(totalGotScore / totalRecords) : 0;
    const scoreRate = item.score > 0 && totalRecords > 0
      ? roundToTwo(totalGotScore / (item.score * totalRecords))
      : 0;

    return {
      questionId: item.questionId,
      sortOrder: item.sortOrder,
      type: item.question.type,
      content: item.question.content,
      score: item.score,
      difficulty: item.question.difficulty,
      subject: item.question.subject,
      correctCount,
      wrongCount,
      unansweredCount,
      ungradedCount,
      accuracyRate,
      avgScore,
      scoreRate,
      isObjective: objective,
    };
  });
}

export function calculateDimensionStats(
  questionStats: QuestionStatItem[],
  dimension: 'type' | 'difficulty' | 'subject'
): DimensionStatItem[] {
  const groups: Record<string, QuestionStatItem[]> = {};

  for (const qs of questionStats) {
    const key = String(qs[dimension]);
    if (!groups[key]) {
      groups[key] = [];
    }
    groups[key].push(qs);
  }

  const result: DimensionStatItem[] = [];
  for (const [name, items] of Object.entries(groups)) {
    const questionCount = items.length;
    const totalScore = items.reduce((sum, item) => sum + item.score, 0);
    const totalCorrectCount = items.reduce((sum, item) => sum + item.correctCount, 0);
    const totalUngradedCount = items.reduce((sum, item) => sum + item.ungradedCount, 0);

    const totalAvgScore = items.reduce((sum, item) => sum + item.avgScore, 0);
    const avgScore = questionCount > 0 ? roundToTwo(totalAvgScore / questionCount) : 0;

    const gradedTotal = items.reduce(
      (sum, item) => sum + item.correctCount + item.wrongCount,
      0
    );
    const accuracyRate = gradedTotal > 0
      ? roundToTwo(totalCorrectCount / gradedTotal)
      : 0;

    const scoreRate = totalScore > 0 ? roundToTwo(totalAvgScore / totalScore) : 0;

    result.push({
      name,
      questionCount,
      totalScore,
      correctCount: totalCorrectCount,
      ungradedCount: totalUngradedCount,
      accuracyRate,
      avgScore,
      scoreRate,
    });
  }

  return result;
}
