import prisma from '../lib/prisma';
import { QuestionType, Difficulty } from '../types';

export interface AutoGenerateParams {
  subject: string;
  questionTypes: QuestionType[];
  totalScore: number;
  difficulty?: Difficulty;
  title?: string;
  duration?: number;
  userId: number;
}

export interface AutoGenerateResult {
  questionId: number;
  score: number;
  sortOrder: number;
}

export async function generatePaperItems(params: AutoGenerateParams): Promise<{
  items: AutoGenerateResult[];
  actualTotal: number;
}> {
  const { subject, questionTypes, totalScore, difficulty } = params;

  const where: any = { subject };
  if (difficulty) where.difficulty = difficulty;
  if (questionTypes.length > 0) where.type = { in: questionTypes };

  const questions = await prisma.question.findMany({ where });
  if (questions.length === 0) {
    return { items: [], actualTotal: 0 };
  }

  const shuffled = questions.sort(() => Math.random() - 0.5);

  let remainingScore = totalScore;
  const selectedItems: AutoGenerateResult[] = [];
  let sortOrder = 1;

  for (const q of shuffled) {
    if (remainingScore <= 0) break;
    const score = Math.min(q.score, remainingScore);
    selectedItems.push({ questionId: q.id, score, sortOrder });
    remainingScore -= score;
    sortOrder++;
  }

  const actualTotal = selectedItems.reduce((sum, item) => sum + item.score, 0);

  return { items: selectedItems, actualTotal };
}

export async function createAutoGeneratedPaper(params: AutoGenerateParams) {
  const { items, actualTotal } = await generatePaperItems(params);

  if (items.length === 0) {
    return null;
  }

  const title = params.title || `${params.subject}自动生成试卷`;
  const description = `自动生成 - 难度: ${params.difficulty || '混合'} - 总分: ${actualTotal}`;
  const duration = params.duration || Math.ceil(items.length * 2);

  const paper = await prisma.paper.create({
    data: {
      title,
      description,
      totalScore: actualTotal,
      duration,
      createdBy: params.userId,
      items: { create: items },
    },
    include: { items: { include: { question: true }, orderBy: { sortOrder: 'asc' } } },
  });

  return paper;
}

export async function updatePaperWithAutoGenerate(paperId: number, params: Omit<AutoGenerateParams, 'userId' | 'title' | 'duration'>) {
  const existing = await prisma.paper.findUnique({ where: { id: paperId } });
  if (!existing) {
    return null;
  }

  const { items, actualTotal } = await generatePaperItems({
    ...params,
    userId: existing.createdBy,
  });

  if (items.length === 0) {
    return null;
  }

  await prisma.paperItem.deleteMany({ where: { paperId } });
  const paper = await prisma.paper.update({
    where: { id: paperId },
    data: {
      totalScore: actualTotal,
      items: { create: items },
    },
    include: { items: { include: { question: true }, orderBy: { sortOrder: 'asc' } } },
  });

  return paper;
}

export function calculateExamScore(
  paperItems: Array<{
    id: number;
    questionId: number;
    score: number;
    question: { type: string; answer: string };
  }>,
  answers: Record<number, string> | undefined,
): number {
  let totalScore = 0;

  for (const item of paperItems) {
    const userAnswer = answers ? answers[item.questionId] : undefined;
    if (userAnswer !== undefined && userAnswer !== null && userAnswer !== '') {
      const correctAnswer = item.question.answer;
      if (
        item.question.type === 'SINGLE_CHOICE' ||
        item.question.type === 'TRUE_FALSE' ||
        item.question.type === 'FILL_BLANK'
      ) {
        if (String(userAnswer).trim().toLowerCase() === String(correctAnswer).trim().toLowerCase()) {
          totalScore += item.score;
        }
      } else if (item.question.type === 'MULTIPLE_CHOICE') {
        const userSorted = String(userAnswer)
          .split(',')
          .map((s) => s.trim())
          .sort()
          .join(',');
        const correctSorted = String(correctAnswer)
          .split(',')
          .map((s) => s.trim())
          .sort()
          .join(',');
        if (userSorted === correctSorted) {
          totalScore += item.score;
        }
      }
    }
  }

  return totalScore;
}
