import Router from '@koa/router';
import prisma from '../lib/prisma';
import { authMiddleware } from '../middleware/auth';
import { success, badRequest, notFound } from '../utils/response';
import { getPaginationParams, buildPaginatedResult } from '../utils/pagination';
import { createAutoGeneratedPaper, updatePaperWithAutoGenerate } from '../services/paperService';
import { QuestionType, Difficulty } from '../types';

const router = new Router({ prefix: '/api/papers' });

router.get('/', async (ctx) => {
  const { page, pageSize, skip, take } = getPaginationParams(ctx.query);
  const keyword = ctx.query.keyword as string;

  const where: any = {};
  if (keyword) {
    where.title = { contains: keyword };
  }

  const [total, list] = await Promise.all([
    prisma.paper.count({ where }),
    prisma.paper.findMany({
      where,
      include: {
        user: { select: { id: true, name: true } },
        _count: { select: { items: true } },
      },
      skip,
      take,
      orderBy: { id: 'desc' },
    }),
  ]);

  success(ctx, buildPaginatedResult(list, total, page, pageSize));
});

router.get('/:id', async (ctx) => {
  const id = Number(ctx.params.id);
  const paper = await prisma.paper.findUnique({
    where: { id },
    include: {
      user: { select: { id: true, name: true } },
      items: {
        include: { question: true },
        orderBy: { sortOrder: 'asc' },
      },
    },
  });

  if (!paper) {
    notFound(ctx, '试卷');
    return;
  }

  success(ctx, paper);
});

router.post('/', authMiddleware, async (ctx) => {
  const { title, description, duration, items } = ctx.request.body as {
    title?: string;
    description?: string;
    duration?: number;
    items?: Array<{ questionId: number; score: number; sortOrder?: number }>;
  };
  const userId = ctx.state.user.id;

  if (!title || !duration || !items || !items.length) {
    badRequest(ctx, '缺少必填字段');
    return;
  }

  const totalScore = items.reduce((sum: number, item: any) => sum + (item.score || 0), 0);

  const paper = await prisma.paper.create({
    data: {
      title,
      description,
      totalScore,
      duration,
      createdBy: userId,
      items: {
        create: items.map((item: any, index: number) => ({
          questionId: item.questionId,
          sortOrder: item.sortOrder || index + 1,
          score: item.score,
        })),
      },
    },
    include: { items: true },
  });

  success(ctx, paper);
});

router.put('/:id', authMiddleware, async (ctx) => {
  const id = Number(ctx.params.id);
  const { title, description, duration, items } = ctx.request.body as {
    title?: string;
    description?: string;
    duration?: number;
    items?: Array<{ questionId: number; score: number; sortOrder?: number }>;
  };

  const existing = await prisma.paper.findUnique({ where: { id } });
  if (!existing) {
    notFound(ctx, '试卷');
    return;
  }

  if (items && items.length > 0) {
    await prisma.paperItem.deleteMany({ where: { paperId: id } });

    const totalScore = items.reduce((sum: number, item: any) => sum + (item.score || 0), 0);

    const paper = await prisma.paper.update({
      where: { id },
      data: {
        title: title || existing.title,
        description: description !== undefined ? description : existing.description,
        duration: duration || existing.duration,
        totalScore,
        items: {
          create: items.map((item: any, index: number) => ({
            questionId: item.questionId,
            sortOrder: item.sortOrder || index + 1,
            score: item.score,
          })),
        },
      },
      include: { items: true },
    });

    success(ctx, paper);
  } else {
    const data: any = {};
    if (title) data.title = title;
    if (description !== undefined) data.description = description;
    if (duration) data.duration = duration;

    const paper = await prisma.paper.update({
      where: { id },
      data,
      include: { items: true },
    });

    success(ctx, paper);
  }
});

router.delete('/:id', authMiddleware, async (ctx) => {
  const id = Number(ctx.params.id);

  const existing = await prisma.paper.findUnique({ where: { id } });
  if (!existing) {
    notFound(ctx, '试卷');
    return;
  }

  await prisma.paper.delete({ where: { id } });
  success(ctx);
});

router.post('/auto-generate', authMiddleware, async (ctx) => {
  const { subject, questionTypes, totalScore, difficulty, title, duration } = ctx.request.body as {
    subject?: string;
    questionTypes?: QuestionType[];
    totalScore?: number;
    difficulty?: Difficulty;
    title?: string;
    duration?: number;
  };
  const userId = ctx.state.user.id;

  if (!subject || !questionTypes || !totalScore) {
    badRequest(ctx, '缺少必填参数（subject, questionTypes, totalScore）');
    return;
  }

  const paper = await createAutoGeneratedPaper({
    subject,
    questionTypes,
    totalScore,
    difficulty,
    title,
    duration,
    userId,
  });

  if (!paper) {
    badRequest(ctx, '无法生成试卷，请调整参数或检查题库中是否有符合条件的题目');
    return;
  }

  success(ctx, paper);
});

router.post('/:id/auto-generate', authMiddleware, async (ctx) => {
  const id = Number(ctx.params.id);
  const { subject, questionTypes, totalScore, difficulty } = ctx.request.body as {
    subject?: string;
    questionTypes?: QuestionType[];
    totalScore?: number;
    difficulty?: Difficulty;
  };

  if (!subject || !questionTypes || !totalScore) {
    badRequest(ctx, '缺少必填参数（subject, questionTypes, totalScore）');
    return;
  }

  const paper = await updatePaperWithAutoGenerate(id, {
    subject,
    questionTypes,
    totalScore,
    difficulty,
  });

  if (!paper) {
    notFound(ctx, '试卷');
    return;
  }

  success(ctx, paper);
});

export default router;
